spring:
  application:
    name: digital-marketing-agency-backend
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}

server:
  port: ${PORT:8080}
  forward-headers-strategy: framework

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION:86400000}